[package]
name = "lib_comm"
version = "0.1.0"
authors = ["simonakpoveso"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"